spring:
  application:
    name: expendituremanagement

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  config:
    import: optional:dotenv://


  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


system:
  security:
    secret: ${JWT_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
