spring:
  datasource:
    url: jdbc:h2:mem:prodDb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

system:
  security:
    secret: ADHSHS3243845FVXHJSDhdsau
