spring:
  application:
    name: expendituremanagement

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  config:
    import: optional:dotenv://

system:
  security:
    secret: ${JWT_SECRET}

