name: Deploy CI/CD for Expense Control API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Criar arquivo .env com secrets
        run: |
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test
